"""Constants for tests."""

MOCK_API_KEY = "FakeApiKey"
MOCK_SERIAL_NUMBER = "FP-04-123456"
MOCK_MODBUS_HOST = "127.0.0.1"
MOCK_MODBUS_PORT = 502
MOCK_MODBUS_ADDRESS = 1
MOCK_CONFIG_ENTRY_ID = "test_entry_xtherma"