#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
python3 -m pip install --requirement dev-requirements.txt
sudo apt-get update
sudo apt-get install -y --no-install-recommends iputils-ping
